```{r}
library(dplyr)
library(ggplot2)
library(scales)
library(cowplot)
library(stringr)
```

```{r}
data <- read.csv("data_science_salaries.csv")
```

```{r}
data <- data %>%
  select(-salary, -salary_currency)
```
filter(job_title == 'Data Scientist' & employment_type == 'Full-time') %>%
```{r}
plot1 <- data %>%
  filter(job_title %in% c('Data Scientist',
                          'Director of Data Science',
                          'Data Science Manager',
                          'Head of Data Science',
                          'Lead Data Scientist',
                          'Data Science Practitioner',
                          'Managing Director Data Science',
                          'Data Science Consultant',
                          'AI Scientist',
                          'Data Architect',
                          'Data Engineer',
                          'Data Analyst'),
         company_location == 'United States',
         employee_residence == 'United States') %>%
  group_by(job_title) %>%
  summarise(mean_salary = mean(salary_in_usd, na.rm = TRUE))

plot1$job_title <- gsub('Director of Data Science', 'Director of\nData Science', plot1$job_title)
plot1$job_title <- gsub("Data Science Manager", "Data Science\nManager", plot1$job_title)
plot1$job_title <- gsub('Data Science Practitioner', 'Data Science\nPractitioner', plot1$job_title)
plot1$job_title <- gsub('Managing Director Data Science', 'Managing Director\nof Data Science', plot1$job_title)
plot1$job_title <- gsub('Data Science Consultant', 'Data Science\nConsultant', plot1$job_title)
plot1$job_title <- gsub('Head of Data Science', 'Head of\nData Science', plot1$job_title)

salary_label <- function(salary) {
  paste0("$", round(salary / 1000, 0), "k")
}

plot1 %>%
  ggplot(aes(x = reorder(job_title, mean_salary), y = mean_salary)) +
  geom_col(width = 0.7, fill='turquoise4', alpha=0.9) +
  geom_text(aes(label = scales::dollar(mean_salary)), vjust = -1, size = 2.1, color = "white") + 
  labs(title = "Mean Total Salary by Job Title in the USA",
       subtitle = "Including Both Full-Time and Part-Time Employment Types",
       x = "Job Title",
       y = "Mean Salary in USD\n") +
  theme_minimal() +
  scale_y_continuous(labels=salary_label, breaks = seq(0, 300000, 50000), limits=c(0, 300000)) +
  theme(axis.text.x = element_text(angle = 40, hjust = 1, vjust = 1, size = 8),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=0.05),
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill='gray15', color="NA"),
        axis.text = element_text(color='white', size=8),
        plot.title = element_text(color='white', size=14),
        plot.subtitle = element_text(color='white', size=8, vjust=2),
        axis.title = element_text(color='turquoise4', size = 8))

```