```{r}
# Load necessary libraries for data manipulation and visualization
library(dplyr)
library(ggplot2)
library(scales)
```

```{r}
# Read the dataset containing salary information
data <- read.csv("data/data_science_salaries.csv")
```

```{r}
# Remove unnecessary columns: salary and salary_currency
data <- data %>%
  select(-salary, -salary_currency)
```

```{r}
# Define a custom label function for formatting salary values as "$100k"
salary_label <- function(salary) {
  paste0("$", round(salary / 1000, 0), "k")
}
```

```{r}
# Prepare the data for plotting:
# Filter for observations in the United States and summarize mean salaries by work model and year
salary_trends_plot_data <- data %>%
  filter(company_location == 'United States') %>%
  group_by(work_models, work_year) %>%
  summarise(mean_salary = mean(salary_in_usd), n=n())
```
```{r}
# Create the plot
salary_trends_plot <- salary_trends_plot_data %>%
  ggplot(aes(work_year, mean_salary, color=work_models)) +
  geom_line(show.legend = FALSE) +
  geom_point(shape = 23, 
             size = 4, 
             aes(color = work_models, fill = work_models)) +
  theme_minimal() +
  scale_y_continuous(labels=salary_label, 
                     breaks = seq(100000, 300000, 25000), 
                     limits=c(100000, 225000)) +
  scale_x_continuous(position='top') +
  scale_color_manual(values = c("On-site" = "turquoise3", 
                                "Hybrid" = "gold3", 
                                "Remote" = "plum3")) +
  scale_fill_manual(values = c("On-site" = "turquoise4", 
                               "Hybrid" = "gold4", 
                               "Remote" = "plum4")) +
  labs(title='Data Science Salary Trends in the USA',
       subtitle = "Categorized by Work Model\nFor Years 2020 through 2024",
       x=NULL,
       y = "Mean Salary in USD\n",
       caption = "Source of the data: KAGGLE Data Science Salaries 2024") +
  theme(axis.text.x = element_text(size = 8), 
        axis.text.y = element_markdown(margin = margin(r = -15), face = "italic"),
        panel.grid.major = element_line(size=0.05),
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = 'gray15'),
        axis.text = element_text(color = 'white'),
        plot.title = element_text(color = 'white', size = 14),
        plot.subtitle = element_text(color = 'white', size = 8, vjust = 2.5, face = "italic"),
        axis.title.y = element_text(vjust=-1.2, color='turquoise4', size = 8, face = "italic"),
        plot.caption = element_text(color='gray70', size=6),
        legend.position = "bottom",
        legend.text = element_text(color = "white", size=8, face = "italic"),
        legend.title = element_blank())
```

```{r}
# Display the plot
salary_trends_plot
```
